version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  ignore:
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.4.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.2.0
  - dependency-name: gatsby-plugin-preact
    versions:
    - 5.2.0
  - dependency-name: gatsby-cli
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.2.0
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 3.2.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.2.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
    - 3.2.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.2.0
  - dependency-name: preact-render-to-string
    versions:
    - 5.1.18
